repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: opa-check
        name: OPA Policy Check
        entry: opa check --ignore custom/ .
        language: system
        pass_filenames: false
        files: \.rego$
        exclude: ^custom/

    -   id: regal-lint
        name: Regal Lint
        entry: regal lint --ignore-files custom/ .
        language: system
        pass_filenames: false
        files: \.rego$
        exclude: ^custom/
