# METADATA
# description: |
#   Reading a declared fact, with who asserted it and whether it still holds.
#
#   A declaration is not a measurement. Nobody can observe whether a conformity
#   assessment was completed or whether a person can halt the system, so a
#   person asserts it and the library takes their word. 170 of the 185 fields
#   the EU AI Act policies read are of that kind.
#
#   Taking someone's word is reasonable. Taking it forever is not. An assertion
#   that CE marking was affixed, made two years ago against a system that has
#   changed forty times since, reads in the input document exactly like one made
#   this morning. It is worse than a missing declaration, because a missing one
#   is visibly missing.
#
#   So a declaration may carry provenance:
#
#       "ce_marking": {"affixed": {
#           "value": true,
#           "asserted_by": "j.smith@example.com",
#           "asserted_at": "2026-03-01T00:00:00Z",
#           "evidence": "https://grc.example.com/attestation/8814",
#           "expires": "2027-03-01T00:00:00Z"
#       }}
#
#   and an expired one resolves to undefined rather than to its value. Not to
#   `false`: the claim has not been refuted, it has gone stale, and a policy
#   with a `default := false` will deny either way while a report can tell the
#   difference between "they said no" and "nobody has said anything lately".
#
#   A bare value still works and always will. Most inputs are written by hand or
#   generated by a tool that has no provenance to offer, and demanding an
#   attestation object everywhere would make the common case worse to serve the
#   rare one.
#
#   The clock is an input. `evaluated_at` is read from the document rather than
#   from `time.now_ns()`, because an evaluation that consults the wall clock is
#   not reproducible: the same bundle and the same input would produce different
#   verdicts on different days with nothing in either to explain why. An auditor
#   re-running last quarter's evidence has to get last quarter's answer.
package helper_functions.declarations

import rego.v1

# METADATA
# description: |
#   The value of a declared fact, or undefined.
#
#   Undefined when the path is absent, when the attestation has expired, or when
#   an attestation object carries no value at all. Callers that need absence to
#   be a definite outcome use `resolve_or`.
resolve(doc, path) := value if {
	raw := object.get(doc, path, null)
	raw != null
	value := _value(doc, raw)
}

_value(_, raw) := raw if {
	not is_object(raw)
}

_value(doc, raw) := raw if {
	is_object(raw)
	not "value" in object.keys(raw)
}

_value(doc, raw) := raw.value if {
	is_object(raw)
	"value" in object.keys(raw)
	not _expired(doc, raw)
}

# METADATA
# description: |
#   The value, or an explicit fallback when the fact is absent or stale.
#
#   For policies that already treat absence as a definite outcome, usually with
#   a sentinel that fails every comparison.
resolve_or(doc, path, fallback) := value if {
	value := resolve(doc, path)
} else := fallback

# METADATA
# description: |
#   True when the fact was declared and has not expired.
# scope: document
default supplied(_, _) := false

supplied(doc, path) if {
	resolve(doc, path) != null
}

# METADATA
# description: |
#   True when a declaration exists but has gone stale. Distinct from absent, so
#   a report can say "re-attest this" rather than "answer this", which are
#   different jobs for different people.
# scope: document
default stale(_, _) := false

stale(doc, path) if {
	raw := object.get(doc, path, null)
	is_object(raw)
	"value" in object.keys(raw)
	_expired(doc, raw)
}

# METADATA
# description: |
#   Who asserted a fact, and when. Empty when the declaration is a bare value,
#   which is the honest answer: nobody recorded it.
attribution(doc, path) := info if {
	raw := object.get(doc, path, null)
	is_object(raw)
	"value" in object.keys(raw)
	info := {k: v |
		some k in ["asserted_by", "asserted_at", "evidence", "expires"]
		v := object.get(raw, k, null)
		v != null
	}
}

_expired(doc, raw) if {
	expires := object.get(raw, "expires", null)
	expires != null
	now := _now(doc)
	now != null
	time.parse_rfc3339_ns(expires) <= now
}

# The evaluation clock, supplied by the caller.
#
# Absent, nothing expires. That is deliberate: an input written by hand or by a
# tool with no notion of time should not have its declarations silently voided
# because it failed to say what day it is. Expiry is a property the caller opts
# into by stating when the evaluation happened.
_now(doc) := ns if {
	stamp := object.get(doc, ["evaluated_at"], null)
	stamp != null
	ns := time.parse_rfc3339_ns(stamp)
}
