#!/usr/bin/env bash
#
# How far does a Hugging Face model card get you toward compliance?
#
# The playground's sample inputs were once loosely called "model cards". They
# are not: a model card documents a model, and almost everything these policies
# read is a fact about the organisation around it. That felt true and was worth
# measuring rather than asserting, so every declared fact the library evaluates
# is classified in docs/model-card-classification.json against what a card
# structurally contains.
#
# The classification is a judgement. It is written out field by field, with a
# reason for each, so it can be argued with rather than trusted. The counts in
# the generated document are computed from it and never typed.
#
# Usage: model-card-coverage.sh [--check]
#   Writes docs/model-cards-vs-compliance.md, or with --check fails if that file
#   is stale, or if the classification names a field no policy reads.

set -euo pipefail

cd "$(dirname "$0")/.."

CLASSIFICATION="docs/model-card-classification.json"
OUT="docs/model-cards-vs-compliance.md"
MANIFEST="dist/playground/manifest.json"

if [ ! -f "${MANIFEST}" ]; then
	echo "Building playground artefacts first…" >&2
	scripts/build-playground.sh >/dev/null
fi

VERSION="$(cat VERSION)"

# The classification must describe the shipped manifest exactly. If a policy
# starts reading a new field, this analysis is stale and should say so rather
# than quietly reporting against a smaller denominator.
unknown="$(jq -r --slurpfile c "${CLASSIFICATION}" '
	[.frameworks[].policies[].declared_fields[]] | unique as $fields
	| (($c[0].answerable | keys) + ($c[0].partial | keys))
	| map(select(. as $k | ($fields | index($k)) | not))
	| .[]
' "${MANIFEST}")"

if [ -n "${unknown}" ]; then
	echo "error: classification names fields that no policy reads:" >&2
	printf '  %s\n' ${unknown} >&2
	echo "" >&2
	echo "Remove them from ${CLASSIFICATION}, or check whether a policy changed." >&2
	exit 1
fi

doc="$(jq -r --slurpfile c "${CLASSIFICATION}" --arg version "${VERSION}" '
	($c[0].answerable) as $A | ($c[0].partial) as $P
	| [.frameworks[].policies[].declared_fields[]] | unique as $fields
	| ($fields | map(select($A[.]))) as $ans
	| ($fields | map(select($P[.] and ($A[.] | not)))) as $par
	| ($fields | map(select(($A[.] | not) and ($P[.] | not)))) as $non
	| ($fields | length) as $total
	| def pct($n): (($n * 100 / $total) | round | tostring);
	  [
	"# How far does a model card get you toward compliance?",
	"",
	"**Generated by `scripts/model-card-coverage.sh` from `docs/model-card-classification.json` and the playground manifest. Do not edit by hand.**",
	"",
	"GOPAL v\($version) evaluates **\($total) declared facts** about an AI system across the frameworks shipped to the [validation preview](https://principledevolution.ai/playground). A declared fact is one no tool can measure for you — whether a CE marking was affixed, whether logs are retained for ten years.",
	"",
	"A Hugging Face model card is often assumed to be the document that answers this. Every one of those facts is classified below against what a card structurally contains: its YAML metadata (`license`, `datasets`, `metrics`, `model-index`, `base_model`, `pipeline_tag`, `library_name`) and the sections of the standard template.",
	"",
	"## Result",
	"",
	"| | Facts | Share |",
	"| --- | --- | --- |",
	"| **Answerable from a model card** | \($ans | length) | \(pct($ans | length))% |",
	"| **Partially informed by one** | \($par | length) | \(pct($par | length))% |",
	"| **Untouched by one** | \($non | length) | \(pct($non | length))% |",
	"| Total | \($total) | |",
	"",
	"A complete, well-written model card answers **\($ans | length) of \($total)** outright and gives you material for \($par | length) more. The remaining **\($non | length) (\(pct($non | length))%)** are not in a model card because they are not about the model. They are about the organisation around it: who signed the declaration of conformity, whether a notified body was involved, whether the deployer told the affected workers, whether logs are kept for six months.",
	"",
	"## What a card does answer",
	"",
	"| Declared fact | Where in the card |",
	"| --- | --- |"
	]
	+ ($ans | map("| `\(.)` | \($A[.]) |"))
	+ [
	"",
	"## What it partially informs",
	"",
	"These are the ones worth arguing about. In each case the card raises the topic without asserting the fact, and the distinction matters: a Bias, Risks and Limitations section is not the same claim as \"a bias assessment was completed\".",
	"",
	"| Declared fact | Why it is only partial |",
	"| --- | --- |"
	]
	+ ($par | map("| `\(.)` | \($P[.]) |"))
	+ [
	"",
	"## What it does not reach",
	"",
	"Grouped by the part of the input they belong to.",
	"",
	"| Group | Facts | Examples |",
	"| --- | --- | --- |"
	]
	+ ($non
		| group_by(split(".")[0])
		| sort_by(-length)
		| map("| `\(.[0] | split(".")[0])` | \(length) | " +
			((.[0:3] | map("`" + (split(".")[1:] | join(".")) + "`") | join(", "))
			 + (if length > 3 then ", …" else "" end)) + " |"))
	+ [
	"",
	"## Method and limits",
	"",
	"- The classification is a judgement, not a measurement, which is why every field is listed with its reason rather than summarised. The `partial` list is where to disagree.",
	"- It assumes a **complete** card following the standard template. Most published cards are thinner, so real coverage is lower.",
	"- It counts distinct declared facts, not policies. Fields read by more than one policy are counted once.",
	"- Measured metrics and policy thresholds are excluded: neither is something a person declares.",
	"- `--check` fails if the classification names a field no policy reads, so this cannot silently drift from the library.",
	""
	]
	| join("\n")
' "${MANIFEST}")"

if [ "${1:-}" = "--check" ]; then
	if [ ! -f "${OUT}" ] || [ "$(cat "${OUT}")" != "${doc}" ]; then
		echo "error: ${OUT} is out of date. Run: scripts/model-card-coverage.sh" >&2
		exit 1
	fi
	echo "${OUT} is up to date."
else
	printf '%s\n' "${doc}" >"${OUT}"
	jq -r --slurpfile c "${CLASSIFICATION}" '
		[.frameworks[].policies[].declared_fields[]] | unique | length as $t
		| ($c[0].answerable | length) as $a | ($c[0].partial | length) as $p
		| "Wrote docs/model-cards-vs-compliance.md — \($t) facts: \($a) answerable, \($p) partial, \($t - $a - $p) untouched."
	' "${MANIFEST}"
fi
